### ISSUE TITLE
User.authenticate broken

### ISSUE THREAD

**Issue by joelmoss** [chef-boneyard/chef-api#22]
Seems that `User.authenticate` is not working...

``` ruby
irb(main):052:0> ChefAPI::Resource::User.authenticate username: 'joelmoss', password: 'something'
             ChefAPI::Connection | ===> POST /authenticate_user...
             ChefAPI::Connection |      Chef flavor: :open_source
             ChefAPI::Connection | ===> Building URI...
             ChefAPI::Connection |      Detected URI is relative
             ChefAPI::Connection |      Appending /authenticate_user to https://X.com
             ChefAPI::Connection | ===> Adding request headers...
             ChefAPI::Connection |      Accept: application/json
             ChefAPI::Connection |      Content-Type: application/json
             ChefAPI::Connection |      Connection: keep-alive
             ChefAPI::Connection |      Keep-Alive: 30
             ChefAPI::Connection |      User-Agent: ChefAPI Ruby Gem 0.5.0
             ChefAPI::Connection |      X-Chef-Version: 11.4.0
             ChefAPI::Connection | ===> Detected form data
             ChefAPI::Connection | ===> Adding signed header authentication...
         ChefAPI::Authentication | ===> Parsing private key...
         ChefAPI::Authentication |      Detected private key is the path to a file
             ChefAPI::Connection |      X-Ops-Sign: algorithm=sha1;version=1.0;
             ChefAPI::Connection |      X-Ops-Userid: chef-webui
             ChefAPI::Connection |      X-Ops-Timestamp: 2014-07-23T22:22:24Z
             ChefAPI::Connection |      X-Ops-Content-Hash: MX2/hAzVT2IPTTXtlKrGf9AzXOo=
             ChefAPI::Connection |      X-Ops-Authorization-1: x
             ChefAPI::Connection |      X-Ops-Authorization-2: x
             ChefAPI::Connection |      X-Ops-Authorization-3: x
             ChefAPI::Connection |      X-Ops-Authorization-4: x
             ChefAPI::Connection |      X-Ops-Authorization-5: x
             ChefAPI::Connection |      X-Ops-Authorization-6: x
             ChefAPI::Connection |      Raw response:
             ChefAPI::Connection |      {"error":["internal service error"]}
             ChefAPI::Connection | ===> Parsing response as error...
             ChefAPI::Connection |      Detected error response as JSON
             ChefAPI::Connection |      Parsing error response as JSON
ChefAPI::Error::HTTPServerUnavailable: The Chef Server is currently unavailable or is not currently accepting client connections. Please ensure the server is accessible via ping or telnet on your local network. If this error persists, please contact your network administrator.

    from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-api-0.5.0/lib/chef-api/connection.rb:425:in `error'
    from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-api-0.5.0/lib/chef-api/connection.rb:282:in `block in request'
    from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/2.1.0/net/http.rb:853:in `start'
    from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-api-0.5.0/lib/chef-api/connection.rb:268:in `request'
    from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-api-0.5.0/lib/chef-api/connection.rb:122:in `post'
    from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-api-0.5.0/lib/chef-api/resources/user.rb:78:in `authenticate'
    from (irb):52
    from /usr/local/opt/rbenv/versions/2.1.2/bin/irb:11:in `<main>'
```

Ridley's `user.authenticate` method works with the same server and credentials.

thx

**Comment by aabognah** [comment]
Hi @sethvargo . I am trying to use the authenticate_user api call with our chef server (open source locally hosted) but I keep getting (404 Not Found). Do you know if this call is available for open source chef?
